apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cricket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cricket
  template:
    metadata:
      labels:
        app: flask-cricket
    spec:
      containers:
      - name: flask-cricket
        image: ajproduct/flask-cricket:latest
        ports:
        - containerPort: 5000

